CREATE TABLE planning.clients
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name  VARCHAR(100),
    email VARCHAR(255),
    phone VARCHAR(15),
    CONSTRAINT pk_clients PRIMARY KEY (id)
);

CREATE TABLE planning.projects
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title              VARCHAR(100),
    description        VARCHAR(255),
    platform           VARCHAR(60),
    status             VARCHAR(60),
    type               VARCHAR(100),
    minimum_value      DECIMAL,
    maximum_value      DECIMAL,
    closed_value       DECIMAL,
    delivery_forecast  date,
    delivery_date      date,
    user_id            UUID                                    NOT NULL,
    client_id          BIGINT                                  NOT NULL,
    roi_calculation_id BIGINT,
    CONSTRAINT pk_projects PRIMARY KEY (id)
);

CREATE TABLE planning.roi_calculations
(
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    value_in_coins         INTEGER,
    project_type           SMALLINT,
    coin_unit_cost         DECIMAL,
    probability_of_closing DOUBLE PRECISION,
    expected_value         DECIMAL,
    CONSTRAINT pk_roi_calculations PRIMARY KEY (id)
);

CREATE TABLE identity.users
(
    id         UUID NOT NULL,
    name       VARCHAR(100),
    email      VARCHAR(255),
    password   VARCHAR(255),
    occupation VARCHAR(60),
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE planning.clients
    ADD CONSTRAINT uc_clients_email UNIQUE (email);

ALTER TABLE planning.projects
    ADD CONSTRAINT uc_projects_roi_calculation UNIQUE (roi_calculation_id);

ALTER TABLE planning.projects
    ADD CONSTRAINT FK_PROJECTS_ON_CLIENT FOREIGN KEY (client_id) REFERENCES planning.clients (id);

ALTER TABLE planning.projects
    ADD CONSTRAINT FK_PROJECTS_ON_ROI_CALCULATION FOREIGN KEY (roi_calculation_id) REFERENCES planning.roi_calculations (id);

ALTER TABLE planning.projects
    ADD CONSTRAINT FK_PROJECTS_ON_USER FOREIGN KEY (user_id) REFERENCES identity.users (id);

ALTER TABLE identity.users
    ADD CONSTRAINT uc_users_email UNIQUE (email);